DECLARE
  V_MONTH VARCHAR2(100);
BEGIN
  FOR V_NUM IN 201703 .. 201712 LOOP
    V_MONTH := TO_CHAR(V_NUM); 
      INSERT INTO XXHB_MJH.TMP_RED_BAG_INFO
        SELECT PRESENT_FEE, PROMOTION_ID, PROMOTION_NAME
          FROM DW.DW_V_USER_POLICY_PRESENT_FEE A
         WHERE ACCT_MONTH = V_MONTH
           AND PROMOTION_TYPE_NAME = 'ÒíÖ§¸¶ºì°ü¿¨'
         GROUP BY PRESENT_FEE, PROMOTION_ID, PROMOTION_NAME;
      COMMIT;
    END LOOP;
  END;

create table XXHB_MJH.TMP_RED_BAG_INFO_2 as 
select distinct a.*  from XXHB_MJH.TMP_RED_BAG_INFO a


--Ì×²ÍÂë±í
create table DIM.DIM_REDBAG_NO as
SELECT A.PROMOTION_ID, A.PROMOTION_NAME, B.ATTR_VALUE, A.DESCRIBE
  FROM CRM_DSG.SALES_PROMOTION@HBODS      A,
       CRM_DSG.SALES_PROMOTION_ITEM@HBODS B
 WHERE SUBSIDY_TYPE IN (26)
   AND B.PROMOTION_ID = A.PROMOTION_ID
   AND B.ITEM_ATTR_ID IN (9103, 10504, 20037);
   
SELECT USER_NO,
       PRESENT_FEE,
       PROMOTION_ID,
       PROMOTION_NAME,
       EFF_DATE,
       EXP_DATE
  FROM DW.DW_V_USER_POLICY_PRESENT_FEE A
 WHERE ACCT_MONTH = '201807'
   AND PROMOTION_TYPE_NAME = 'ÒíÖ§¸¶ºì°ü¿¨'
   
           
           
           
