create or replace view dim.dim_zq_huaxiao_info as
select "AREA_NO","CITY_NO","HUAXIAO_NO","HUAXIAO_NAME","HUAXIAO_TYPE","HUAXIAO_TYPE_NAME","IF_VALID","UPDATE_USER","UPDATE_DATE","IDX_NO","CREATE_USER","CREATE_DATE","HUAXIAO_TYPE_BIG","HUAXIAO_TYPE_NAME_BIG","MANAGER_LOGINID","MANAGER_LOGINNAME","MANAGER_TELEPHONE" from dim_hx_gx
union all
select "AREA_NO","CITY_NO","HUAXIAO_NO","HUAXIAO_NAME","HUAXIAO_TYPE","HUAXIAO_TYPE_NAME","IF_VALID","UPDATE_USER","UPDATE_DATE","IDX_NO","CREATE_USER","CREATE_DATE","HUAXIAO_TYPE_BIG","HUAXIAO_TYPE_NAME_BIG","MANAGER_LOGINID","MANAGER_LOGINNAME","MANAGER_TELEPHONE" from dim_hx_yw
union all
select "AREA_NO","CITY_NO","HUAXIAO_NO","HUAXIAO_NAME","HUAXIAO_TYPE","HUAXIAO_TYPE_NAME","IF_VALID","UPDATE_USER","UPDATE_DATE","IDX_NO","CREATE_USER","CREATE_DATE","HUAXIAO_TYPE_BIG","HUAXIAO_TYPE_NAME_BIG","MANAGER_LOGINID","MANAGER_LOGINNAME","MANAGER_TELEPHONE" from dim_hx_sk
union all
select "AREA_NO","CITY_NO","HUAXIAO_NO","HUAXIAO_NAME","HUAXIAO_TYPE","HUAXIAO_TYPE_NAME","IF_VALID","UPDATE_USER","UPDATE_DATE","IDX_NO","CREATE_USER","CREATE_DATE","HUAXIAO_TYPE_BIG","HUAXIAO_TYPE_NAME_BIG","MANAGER_LOGINID","MANAGER_LOGINNAME","MANAGER_TELEPHONE" from dim.dim_hx_wlw;
