create or replace view dim_zq_channel_huaxiao as
select "AREA_NO","CITY_NO","CHANNEL_NO","CHANNEL_NO_DESC","HUAXIAO_NO","HUAXIAO_NAME","HUAXIAO_TYPE","HUAXIAO_TYPE_NAME","IF_VALID","UPDATE_USER","UPDATE_DATE","IDX_NO","HUAXIAO_TYPE_BIG","HUAXIAO_TYPE_NAME_BIG","IS_DEVELOPER" from dim_hx_yw_channel
union all
select "AREA_NO","CITY_NO","CHANNEL_NO","CHANNEL_NO_DESC","HUAXIAO_NO","HUAXIAO_NAME","HUAXIAO_TYPE","HUAXIAO_TYPE_NAME","IF_VALID","UPDATE_USER","UPDATE_DATE","IDX_NO","HUAXIAO_TYPE_BIG","HUAXIAO_TYPE_NAME_BIG","IS_DEVELOPER" from dim_hx_sk_channel;
