DECLARE
  V_MONTH   VARCHAR2(100);
  V_RETCODE VARCHAR2(100);
  V_RETINFO VARCHAR2(100);
BEGIN  
  FOR V_NUM IN 201801 .. 201807 LOOP
    V_MONTH := TO_CHAR(V_NUM);
    dw.P_TMP_V_USER_HUAXIAO_INFO_ALL(V_MONTH, V_RETCODE, V_RETINFO);
    alldm.P_DM_ZQ_HUAXIAO_INFO_M(V_MONTH, V_RETCODE, V_RETINFO);
    --alldm.p_dm_zq_channel_huaxiao_m(V_MONTH, V_RETCODE, V_RETINFO); 
  END LOOP;    
END;
