SELECT B.AREA_NO, A.*
  FROM (SELECT A.AREA_NO,
               C.AREA_DESCRIPTION AREA_DESCRIPTION,
               C.CITY_NO,
               C.DESCRIPTION CITY_NAME,
               SUM(RING_FUNC_FEE) RING_FUNC_FEE,
               SUM(RING_INFO_FEE) RING_INFO_FEE,
               SUM(MUSIC_DOWN_FEE) MUSIC_DOWN_FEE,
               SUM(MUSIC_VIP_FEE) MUSIC_VIP_FEE,
               SUM(OTHER_MUSIC_FEE) OTHER_MUSIC_FEE,
               SUM(MUSIC_INFO_FEE_SUM) MUSIC_INFO_FEE_SUM,
               SUM(MUSIC_TOTAL_FEE) MUSIC_TOTAL_FEE
          FROM (SELECT *
                  FROM NEW_ALLDM.DM_KKPI_M_SAP_MUSIC_INCO T
                 WHERE T.ACCT_MONTH = '201804'
                   ) A,
               (SELECT * FROM NEW_DMCODE.DMCODE_CITY) C
         WHERE A.CITY_NO = C.CITY_NO
         GROUP BY A.AREA_NO, C.AREA_DESCRIPTION, C.CITY_NO, C.DESCRIPTION) A,
       NEW_DMCODE.DMCODE_AREA B
 WHERE A.AREA_NO = B.AREA_NO(+)
 ORDER BY IDX_NO
