DECLARE
  V_MONTH   VARCHAR2(100);
  V_RETCODE VARCHAR2(100);
  V_RETINFO VARCHAR2(100);
BEGIN 
  FOR V_NUM IN 201806 .. 201806 LOOP
    V_MONTH := TO_CHAR(V_NUM);
    RPT_HBTELE.P_SJZX_WH_CHANNEL_JF_SCORE_M(V_MONTH,'1', V_RETCODE, V_RETINFO);
    mobile_cbzs.P_CBZS_DM_KKPI_M_JIFEN_CHANNEL(V_MONTH, V_RETCODE, V_RETINFO);
    mobile_cbzs.P_CBZS_DM_KKPI_M_DEV_CHANNEL(V_MONTH, V_RETCODE, V_RETINFO);
    mobile_cbzs.P_CBZS_DM_KKPI_M_INCO_CHANNEL(V_MONTH, V_RETCODE, V_RETINFO);
  END LOOP;  
END;
