--分品牌
SELECT TERMINAL_CORP, SUM(CNT)
  FROM (SELECT TERMINAL_CORP, DEVICE_NO,COUNT(*)CNT
          FROM DW_V_USER_TERMINAL_DEVICE_M
         WHERE ACCT_MONTH = '201705' 
           AND REG_DATE > TO_DATE('20170101', 'YYYY-MM-DD')
           AND REG_DATE < TO_DATE('20170601', 'YYYY-MM-DD')
         GROUP BY TERMINAL_CORP, DEVICE_NO
        HAVING COUNT(*) > 1)
 GROUP BY TERMINAL_CORP
 
 
 --分地市
SELECT B.AREA_DESC, SUM(CNT)
  FROM (SELECT AREA_NO,DEVICE_NO,COUNT(*)CNT
          FROM DW_V_USER_TERMINAL_DEVICE_M
         WHERE ACCT_MONTH = '201705' 
           AND REG_DATE > TO_DATE('20170101', 'YYYY-MM-DD')
           AND REG_DATE < TO_DATE('20170601', 'YYYY-MM-DD')
         GROUP BY AREA_NO, DEVICE_NO
        HAVING COUNT(*) > 1) A,
       DIM.DIM_AREA_NO B
 WHERE A.AREA_NO = B.AREA_NO
 GROUP BY B.AREA_DESC, B.IDX_NO
 ORDER BY B.IDX_NO
