select t.*, t.rowid from tmp_majh_0613 t;


CREATE TABLE TMP_MAJH_0613_01 AS
SELECT A.*,
       B.DEVICE_NO,
       B.TERMINAL_CORP,
       B.TERMINAL_MODEL AS MODEL_NEW,
       TO_CHAR(B.REG_DATE,'YYYYMMDDHH24MISS')REG_DATE,
       CASE
         WHEN C.USER_NO IS NOT NULL THEN
          'ÊÇ'
         ELSE
          '·ñ'
       END IS_ONNET
  FROM TMP_MAJH_0613 A,
       (SELECT TERMINAL_CODE, TERMINAL_CORP, TERMINAL_MODEL, DEVICE_NO£¬REG_DATE
          FROM DW.DW_V_USER_TERMINAL_DEVICE_D A
         WHERE ACCT_MONTH = '201806'
           AND DAY_ID = '12') B,
       (SELECT USER_NO, DEVICE_NUMBER
          FROM DW.DW_V_USER_BASE_INFO_DAY C
         WHERE ACCT_MONTH = '201806'
           AND DAY_ID = '12'
           AND IS_ONNET = '1') C
 WHERE A.TERMINAL_CODE = B.TERMINAL_CODE(+)
   AND B.DEVICE_NO = C.DEVICE_NUMBER(+)


--µ¼³ö
select * from TMP_MAJH_0613_01

