create table tmp_majh_qizha_188
(
acct_month varchar2(20),
area_no varchar2(20),
area_no_desc varchar2(20),
city_no varchar2(30),
city_no_desc varchar2(60),
device_number varchar2(20),
INNET_MONTH  varchar2(20),
is_risk_channel  varchar2(20),
call_duration number,
call_cdr number,
zhu_dur_rate number,
zhu_cdr_rate number,
zhu_users_rate number,
zhu_per_dur number,
lower_60_rate number,
lower_15_rate number,
roam_dur_rate number,
long_dur_rate number,
total_fee number,
call_mon_rate number,
is_trans  varchar2(20),
is_ocs  varchar2(20),
cell_rate number,
is_link_risk  varchar2(20),
is_reg_risk  varchar2(20),
is_dinner_risk varchar2(20),
is_low_terminal  varchar2(20),
is_cert_1_n   varchar2(20)
)
