create table TEMP_USER.TMP_HUAXIAO_INFO_M AS
select * from DM_V_HUAXIAO_INFO_M;

TMP_V_HUAXIAO_INFO_M

DROP TABLE DM_V_HUAXIAO_INFO_M;

create table DM_V_HUAXIAO_INFO_M
select * from TMP_V_HUAXIAO_INFO_M
