SELECT COUNT(*)
  FROM (SELECT UPPER(CELL_PHONE) CELL_PHONE
          FROM STAGE.TEMP_GU_BDM_MAJIANHUI T
         WHERE T.CELL_PHONE LIKE 'IP%') A,
       (SELECT DEVICE_NUMBER
          FROM DW.DW_V_USER_BASE_INFO_USER B
         WHERE ACCT_MONTH = '201706'
           AND IS_ONNET = '1'
           AND TELE_TYPE IN ('4', '26')) B
 WHERE A.CELL_PHONE = B.DEVICE_NUMBER
