--动环与能耗匹配异常明细
select * from 
(SELECT distinct  area_name,group_name,room_id,replace(A.RELATION_ID,chr(13),'')RELATION_ID,room_name
          FROM ALLDM.ELEC_STATION_D A
         WHERE ACCT_MONTH = '201807')a,
         (SELECT STATION_ID_A, STATION_ID_B
          FROM (SELECT STATION_ID_A,
                       STATION_ID_B,
                       ROW_NUMBER() OVER(PARTITION BY STATION_ID_A ORDER BY 1) RN
                  FROM DIM.DIM_STATION_REL
                 WHERE STATION_ID_B IS NOT NULL and STATION_ID_B<>'#N/A')
         WHERE RN = 1)b
         where a.relation_id=b.STATION_ID_A(+)
         and b.STATION_ID_A is null;


--PUE异常局站导出
select 
ACCT_MONTH,
AREA_NAME,
GROUP_NAME,
ROOM_NAME,
ELEC_AMOUNT,
DEVICE_AMOUNT,
round(decode(DEVICE_AMOUNT,0,0,ELEC_AMOUNT/DEVICE_AMOUNT),2) as PUE
from
(SELECT ACCT_MONTH,
       B.AREA_NO,
       A.AREA_NAME,
       A.GROUP_NAME,
       A.ROOM_NAME,
       SUM(A.ELEC_AMOUNT) ELEC_AMOUNT,
       SUM(A.DEVICE_AMOUNT) DEVICE_AMOUNT 
  FROM ALLDM.ELEC_STATION_D A, DIM.DIM_AREA_NO B
 WHERE ACCT_MONTH = '201807'
   AND A.AREA_NAME = B.AREA_DESC
 GROUP BY ACCT_MONTH,B.AREA_NO, A.AREA_NAME, A.GROUP_NAME, A.ROOM_NAME)
 where (decode(DEVICE_AMOUNT,0,0,ELEC_AMOUNT/DEVICE_AMOUNT)<1 or 
       decode(DEVICE_AMOUNT,0,0,ELEC_AMOUNT/DEVICE_AMOUNT)>3)
 

--主设备或总耗电量为0
select 
ACCT_MONTH,
AREA_NAME,
GROUP_NAME,
ROOM_NAME,
ELEC_AMOUNT,
DEVICE_AMOUNT,
round(decode(DEVICE_AMOUNT,0,0,ELEC_AMOUNT/DEVICE_AMOUNT),2) as PUE
from
(SELECT ACCT_MONTH,
       B.AREA_NO,
       A.AREA_NAME,
       A.GROUP_NAME,
       A.ROOM_NAME,
       SUM(A.ELEC_AMOUNT) ELEC_AMOUNT,
       SUM(A.DEVICE_AMOUNT) DEVICE_AMOUNT 
  FROM ALLDM.ELEC_STATION_D A, DIM.DIM_AREA_NO B
 WHERE ACCT_MONTH = '201807'
   AND A.AREA_NAME = B.AREA_DESC
 GROUP BY ACCT_MONTH,B.AREA_NO, A.AREA_NAME, A.GROUP_NAME, A.ROOM_NAME)
 where (DEVICE_AMOUNT=0 or ELEC_AMOUNT=0)
 

--全量
SELECT ACCT_MONTH,
       B.AREA_NO,
       A.AREA_NAME,
       A.GROUP_NAME,
       A.ROOM_ID,                 
       A.ROOM_NAME,
       SUM(A.ELEC_AMOUNT) ELEC_AMOUNT,
       SUM(A.DEVICE_AMOUNT) DEVICE_AMOUNT 
  FROM ALLDM.ELEC_STATION_D A, DIM.DIM_AREA_NO B
 WHERE ACCT_MONTH = '201807'
   AND A.AREA_NAME = B.AREA_DESC
 GROUP BY ACCT_MONTH,B.AREA_NO, A.ROOM_ID,A.AREA_NAME, A.GROUP_NAME, A.ROOM_NAME
 
 
